[package]
name = "celeritas-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
celeritas-sys = { path = "./celeritas-sys" }

egui = "0.27.1"
egui_glfw = { git = "https://github.com/omnisci3nce/egui_glfw.git", rev = "67b432695433feb59761f3ae984b966ca3da31db" }
gl = "0.14.0"