name: Check PR

on:
  pull_request:
    branches:
      - master
  push:


jobs:
  check-pr:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: Build
        run: |
          mkdir build
          cmake -GNinja -B build
          cmake --build build
          ctest --test-dir build --output-on-failure

