#pragma once

typedef enum keycode {
  // TODO: add all keycodes
  KEYCODE_SPACE = 32,
  KEYCODE_A = 65,
  KEYCODE_D = 68,
  KEYCODE_S = 83,
  KEYCODE_W = 87,
  KEYCODE_ESCAPE = 256,
  KEYCODE_ENTER = 257,
  KEYCODE_TAB = 258,
  KEYCODE_BACKSPACE = 259,
  KEYCODE_KEY_RIGHT = 262,
  KEYCODE_KEY_LEFT = 263,
  KEYCODE_KEY_DOWN = 264,
  KEYCODE_KEY_UP = 265,
  KEYCODE_MAX = 348
} keycode;